cartpole:
  env_id: CartPole-v1
  input_model_name: carptole1
  output_model_name: cartpole1
  replay_memory_size: 100000
  mini_batch_size: 128
  gamma: 0.99
  tau: 0.005
  learning_rate: 0.0003
  model_save_freq: 100
  max_reward: 300
  max_timestep: 1600
  max_episodes: 3000